name: fliiper_reserver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.19
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/assets/
